[tool.poetry]
name = "dealership-config-models"
version = "0.1.0"
description = ""
authors = ["gpeddle <gpeddle@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
